apiVersion: v1
kind: ConfigMap
metadata:
  name: kitchen-service-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  JAVA_TOOL_OPTIONS: "-Xmx128m -XX:MaxMetaspaceSize=128m"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-service
  labels:
    app: kitchen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-service
  template:
    metadata:
      labels:
        app: kitchen-service
    spec:
      containers:
        - name: kitchen-service
          image: pizza/kitchen-service:latest
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: kitchen-service-config
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kitchen-service
spec:
  selector:
    app: kitchen-service
  ports:
    - port: 8086
      targetPort: 8086
