apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - catalog-service
  - pricing-service
  - rule-service
  - order-service
  - gateway
  - ai-parser-service
  - kitchen-service
  - notification-service
  - admin-service
